version: "3"

services:
    app:
        build:
            context: .
            dockerfile: "docker/${APP_ENV}/app/Dockerfile"
        volumes:
            - .:/var/www
        depends_on:
            - db

    nginx:
        image: nginx
        ports:
            - "8000:80"
        volumes:
            - ./docker/${APP_ENV}/nginx/:/etc/nginx/conf.d
            - ./:/var/www
        depends_on:
            - app

    adminer:
        image: adminer
        restart: always
        ports:
            - "8070:8080"
        container_name: adminer

    db:
        image: postgres
        restart: always
        volumes:
            - ./tmp/db:/var/lib/pgsql
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_USER: '${DB_USERNAME}'
        # ports:
        #     - "8030:5432"
        container_name: pgsql

networks:
    network:
        driver: bridge
